spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.31.225:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.31.225
    port: 6379
server:
  servlet:
    context-path: /sell

wechat:
  mpAppId: ""
  mpAppSecret: ""
  openAppid: ""
  openAppSecret: ""
  mchId: ""
  mchKey: ""
  keyPath: /weixin_cert/h5.p12
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify

project-url:
  wechatMpAuthorize: http://quick.nat300.top
  wechatOpenAuthorize: http://quick.nat300.top
  sell: http://quick.nat300.top
